
logging:
  level:
    com.example: info
    org.springframework: WARN
    com.example.foss.mapper: info
spring:
  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html

    servlet:
      content-type: text/html
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size:  30MB
      max-request-size:  30MB
  devtools:
    restart:
      enabled: true
  redis:
    jedis:
      pool:
        max-active: 10
        min-idle: 5
        max-idle: 10
        max-wait: 2000
    port: 6379
    host: 10.80.13.166
    timeout: 1000

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.80.13.166:3306/foss?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:

      initial-size: 5

      minIdle: 10

      maxActive: 20

      maxWait: 60000
server:
  port: 8080

