
logging:
  level:
    com.example: debug
    org.springframework: WARN
    com.example.foss.mapper: debug
spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html

    servlet:
      content-type: text/html
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size:  30MB
      max-request-size:  30MB
  devtools:
    restart:
      enabled: true
  redis:
    jedis:
      pool:
        max-active: 10
        min-idle: 5
        max-idle: 10
        max-wait: 2000
    port: 6379
    host: 192.168.43.52
    timeout: 1000

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.43.52:3306/foss?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    druid:
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
server:
  port: 8080
mybatis-plus:
  type-aliases-package: com.example.foss.pojo
  mapper-locations: classpath:mapper/*.xml
